-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BOOKSTORE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BOOKSTORE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BOOKSTORE` DEFAULT CHARACTER SET utf8 ;
USE `BOOKSTORE` ;

-- -----------------------------------------------------
-- Table `BOOKSTORE`.`PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKSTORE`.`PUBLISHER` (
  `PUBLISHER_NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(100) NULL,
  `TELEPHONE_NUMBER` VARCHAR(100) NULL,
  PRIMARY KEY (`PUBLISHER_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKSTORE`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKSTORE`.`BOOK` (
  `ISBN` CHAR(13) NOT NULL,
  `PUBLISHER_NAME` VARCHAR(100) NOT NULL,
  `BOOK_TITLE` VARCHAR(100) NOT NULL,
  `BOOKS_IN_STOCK` INT NOT NULL,
  `MIN_THRESHOLD` INT NOT NULL,
  `PUBLICATION_YEAR` YEAR NOT NULL,
  `PRICE` FLOAT NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  INDEX `BOOK_PUBLISHER_FK_idx` (`PUBLISHER_NAME` ASC),
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC),
  CONSTRAINT `BOOK_PUBLISHER_FK`
    FOREIGN KEY (`PUBLISHER_NAME`)
    REFERENCES `BOOKSTORE`.`PUBLISHER` (`PUBLISHER_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKSTORE`.`BOOK_AUTHORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKSTORE`.`BOOK_AUTHORS` (
  `ISBN` CHAR(13) NOT NULL,
  `AUTHOR_NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ISBN`, `AUTHOR_NAME`),
  CONSTRAINT `AUTHORS_BOOK_FK`
    FOREIGN KEY (`ISBN`)
    REFERENCES `BOOKSTORE`.`BOOK` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKSTORE`.`BOOK_ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKSTORE`.`BOOK_ORDERS` (
  `ISBN` CHAR(13) NOT NULL,
  `QUANTITY` INT NOT NULL,
  `PUBLISHER_NAME` VARCHAR(100) NOT NULL,
  `ORDER_NO` INT NOT NULL AUTO_INCREMENT,
  INDEX `ORDERS_PUBLISHER_FK_idx` (`PUBLISHER_NAME` ASC),
  PRIMARY KEY (`ORDER_NO`),
  UNIQUE INDEX `ORDER_NO_UNIQUE` (`ORDER_NO` ASC),
  CONSTRAINT `ORDERS_BOOK_FK`
    FOREIGN KEY (`ISBN`)
    REFERENCES `BOOKSTORE`.`BOOK` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ORDERS_PUBLISHER_FK`
    FOREIGN KEY (`PUBLISHER_NAME`)
    REFERENCES `BOOKSTORE`.`PUBLISHER` (`PUBLISHER_NAME`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `BOOKSTORE`.`BOOKSTORE_USER` (
  `USER_NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) UNIQUE NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `USER_GROUP` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USER_NAME`))
ENGINE = InnoDB;

USE `BOOKSTORE`;

DELIMITER $$
USE `BOOKSTORE`$$
CREATE TRIGGER CHECK_QUANTITY BEFORE UPDATE ON BOOK
FOR EACH ROW
BEGIN
    IF (NEW.BOOKS_IN_STOCK < 0)
    THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Error: Not enough books in stock.';
    END IF;
END$$

USE `BOOKSTORE`$$
CREATE TRIGGER ORDER_BOOK AFTER UPDATE ON BOOK
FOR EACH ROW
BEGIN
    IF (NEW.BOOKS_IN_STOCK < NEW.MIN_THRESHOLD)
    THEN
        INSERT INTO
        BOOK_ORDERS(ISBN, QUANTITY, PUBLISHER_NAME)
        VALUES(NEW.ISBN, NEW.PUBLISHER_NAME, NEW.MIN_THRESHOLD - NEW.BOOKS_IN_STOCK);
    END IF;
END$$

USE `BOOKSTORE`$$
CREATE TRIGGER CHECK_CATEGORY BEFORE INSERT ON BOOK
FOR EACH ROW
BEGIN
    IF ( NEW.CATEGORY NOT IN ('Science', 'Art', 'Religion', 'History', 'Geography') )
    THEN
        SET @MSG_TEXT = CONCAT('Error: Invalid Category (', NEW.CATEGORY, ')') ;
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = @MSG_TEXT;
    END IF;
END$$

USE `BOOKSTORE`$$
CREATE TRIGGER ORDER_CONFIRMED BEFORE DELETE ON BOOK_ORDERS
FOR EACH ROW
BEGIN
    UPDATE BOOK
    SET BOOK.BOOKS_IN_STOCK = BOOK.BOOKS_IN_STOCK + OLD.QUANTITY
    WHERE BOOK.ISBN = OLD.ISBN;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
